### ISSUE TITLE
The corejs reference in the Type defintion causes a TypeScript error

### ISSUE THREAD

**Issue by pjc2007** [jsoendermann/semaphore-async-await#2]
I am using this in an Ionic 2 TypeScript application. The reference to the corejs at the top of the type definition file causes a TypeScript error . Just deleting it fixes it, but of course it comes back as soon as we do a npm install on the project.

Can this be removed?

**Comment by jsoendermann** [comment]
Should be fixed in version 1.3.2, let me know if it's still not working.

**Comment by pjc2007** [comment]
All seems good! Thankyou!
