### ISSUE TITLE
Signature for execute() is wrong

### ISSUE THREAD

**Issue by felixfbecker** [jsoendermann/semaphore-async-await#3]
```ts
async execute<T>(func: () => T): Promise<T> {
```
`func` is awaited, so it should be
```ts
async execute<T>(func: () => T | PromiseLike<T>): Promise<T> {
```
Otherwise TS incorrectly infers the return type as `Promise<Promise<T>>`

Thanks for this awesome package, it's awesome to see simple concepts like Semaphores properly implemented in TypeScript.

**Comment by jsoendermann** [comment]
Thanks for your pull request. I merged it and published a new version to npm.

Glad you find this package useful.
